#spring:
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth8?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456